# Generated by Django 5.0.2 on 2024-03-02 08:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, unique=True)),
                ('Content', models.TextField(max_length=5000)),
                ('Category', models.CharField(max_length=100)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
            ],
        ),
    ]
